### ISSUE TITLE
MySQL 5.6 support

### ISSUE THREAD

**Issue by bploetz** [memsql/ditto#1]
I see from the README that MySQL 5.6 is not currently supported by ditto. Is there a specific incompatibility to the binlog format(s) that changed between 5.5 and 5.6 that would cause ditto to not work with 5.6, or is it simply not tested? Thanks in advance for any info you can share.

**Comment by StabbyCutyou** [comment]
I'm also interested in using this against a 5.6 cluster, and would definitely be interested in seeing what the potential issues are.

**Comment by wjossey** [comment]
ditto

**Comment by carlsverre** [comment]
Very on point wjossey :)

Ditto has not been tested against MySQL 5.6 - so the best thing to do is just try it out.  Please send pull requests or issues if anything comes up.  Thanks!

**Comment by bploetz** [comment]
Great, thanks @carlsverre . We'll take it for a spin on 5.6 and report back if we find any dragons.
